version: '3.1'

services:
    ysf_rabbitmq:
        image: 'bitnami/rabbitmq:3.8'
        ports:
           - '4369'
           - '5672'
           - '25672'
           - '15672'
        volumes:
           - 'ysf_rabbitmq_data:/bitnami'
        depends_on:
           - ysf_postgres
           - ysf_mysql
           - ysf_redis
        restart: always

    ysf_zookeeper:
        image: 'bitnami/zookeeper:3'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
        restart: always

    ysf_kafka:
        image: 'bitnami/kafka:2'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=ysf_zookeeper:2181
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - ysf_zookeeper
          - ysf_postgres
          - ysf_mysql
          - ysf_redis
        restart: always

    ysf_postgres:
        build: postgres
        ports:
          - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgres/fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always

    ysf_mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysqldb-password123
            - MYSQL_USER=mysqldb123
            - MYSQL_PASSWORD=mysqldb-password123
            - MYSQL_DATABASE=mysqldb123
        ports:
          - "3306:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_mariadb:
        image: mariadb:10.4.13
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb-password123
            - MYSQL_USER=mariadb123
            - MYSQL_PASSWORD=mariadb-password123
            - MYSQL_DATABASE=mariadb123
        ports:
            - "3333:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_redis:
        image: redis:latest
        ports:
          - "6379:6379"
        restart: always

    ysf_mongodb:
        image: 'bitnami/mongodb:latest'
        environment:
            - MONGODB_ROOT_PASSWORD=password123
            - ALLOW_EMPTY_PASSWORD=yes
            - MONGODB_SYSTEM_LOG_VERBOSITY=3
            - MONGODB_USERNAME=my_mongodb_user
            - MONGODB_PASSWORD=password123
            - MONGODB_DATABASE=my_mongodb_database
        ports:
          - "27017:27017"
        volumes:
            - 'ysf_mongodb_data:/bitnami'

    ysf_elasticsearch:
        image: 'bitnami/elasticsearch:7'
        environment:
            - ELASTICSEARCH_PORT_NUMBER=9200
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
            - 'ysf_elasticsearch_data:/bitnami/elasticsearch/data'
 
    ysf_php_fpm:
        build: php-fpm
        ports:
            - "9002:9000"
            - "3001:3001"
            - "3000:3000"
            - "82:82"
            - "8222:8222"
            - "8282:8282"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        depends_on:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
            - ysf_elasticsearch
            - ysf_mongodb
            - ysf_kafka
            - ysf_zookeeper
            - ysf_rabbitmq
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
            - ysf_elasticsearch
            - ysf_mongodb
            - ysf_kafka
            - ysf_zookeeper
            - ysf_rabbitmq
        restart: always

    ysf_nginx:
        build: nginx
        ports:
          - "80:80"
          - "8000:8000"
          - "8080:8080"
        depends_on:
            - ysf_php_fpm
        links:
            - ysf_php_fpm
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
        restart: always
        depends_on:
            - ysf_postgres
            - ysf_mysql
        links:
            - ysf_postgres
            - ysf_mysql

volumes:
  ysf_rabbitmq_data:
      driver: local
  ysf_mongodb_data:
      driver: local
  ysf_elasticsearch_data:
      driver: local
