version: '3.1'

services:
    ysf_postgres:
        build: postgres
        ports:
          - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgresabc123
        volumes:
            - ./postgres/fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always

    ysf_redis:
        image: redis:latest
        ports:
          - "6379:6379"
        restart: always

    ysf_adminer:
        image: adminer
        ports:
            - 8071:8080
        depends_on:
            - ysf_postgres
        links:
            - ysf_postgres
        restart: always

