version: '3.1'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - esnet

    elasticsearch2:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        container_name: elasticsearch2
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - "discovery.zen.ping.unicast.hosts=elasticsearch"
        ulimits:
          memlock:
              soft: -1
              hard: -1
        volumes:
          - esdata2:/usr/share/elasticsearch/data
        networks:
          - esnet

    ysf_postgres:
        image: postgres
        ports:
            - '5432:5432'
        restart: always

    ysf_mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysqldb-password123
            - MYSQL_USER=mysqldb123
            - MYSQL_PASSWORD=mysqldb-password123
            - MYSQL_DATABASE=mysqldb123
        ports:
            - "3306:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb-password123
            - MYSQL_USER=mariadb123
            - MYSQL_PASSWORD=mariadb-password123
            - MYSQL_DATABASE=mariadb123
        ports:
            - "3307:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always

    ysf_php_fpm:
        build: php-fpm
        ports:
            - "9002:9000"
            - "3001:3001"
            - "3000:3000"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
            - ysf_redis
            - elasticsearch
            - elasticsearch2
        restart: always

    ysf_nginx:
        build: nginx
        ports:
            - "80:80"
        depends_on:
            - ysf_php_fpm
        links:
            - ysf_php_fpm
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
        restart: always
        depends_on:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
