version: '3.1'

services:
    ysf_rabbitmq:
        image: 'bitnami/rabbitmq:3.8'
        ports:
           - '4369:4369'
           - '5672:5672'
           - '25672:25672'
           - '15672:15672'
        volumes:
           - 'ysf_rabbitmq_data:/bitnami'

    zookeeper:
        image: 'bitnami/zookeeper:3'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
        restart: always
    kafka:
        image: 'bitnami/kafka:2'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper
          - ysf_postgres
          - ysf_mysql
          - ysf_mariadb
          - ysf_redis
        restart: always

    oracle-db:
        image: oracleinanutshell/oracle-xe-11g:latest
        ports:
          - 1521:1521
          - 5500:5500
          - 7780:8080

    ysf_elastic:
        image: ubuntu:16.04
        ports:
            - '9200:9200'
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always
        tty: true

    ysf_postgres:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
        restart: always

    ysf_mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysqldb-password123
            - MYSQL_USER=mysqldb123
            - MYSQL_PASSWORD=mysqldb-password123
            - MYSQL_DATABASE=mysqldb123
        ports:
            - "3306:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb-password123
            - MYSQL_USER=mariadb123
            - MYSQL_PASSWORD=mariadb-password123
            - MYSQL_DATABASE=mariadb123
        ports:
            - "3307:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always

    ysf_php_fpm:
        build: php-fpm
        ports:
            - "9002:9000"
            - "3001:3001"
            - "3000:3000"
            - "82:82"
            - "8222:8222"
            - "8282:8282"

        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
            - ysf_redis
            - ysf_elastic
        restart: always

    ysf_nginx:
        build: nginx
        ports:
            - "80:80"
            - "8000:8000"
            - "8080:8080"
        depends_on:
            - ysf_php_fpm
        links:
            - ysf_php_fpm
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_adminer:
        image: adminer
        restart: always
        ports:
          - 8081:8080
        restart: always
        depends_on:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_mariadb
        
volumes:
  ysf_rabbitmq_data:
    driver: local


