version: '3.1'

services:
    ysf_postgres:
        build: postgres
        ports:
          - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgres/fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always

    ysf_mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password123
            - MYSQL_USER=user123
            - MYSQL_PASSWORD=password123
            - MYSQL_DATABASE=mysqldb
        ports:
          - "3306:3306"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_redis:
        image: redis:latest
        ports:
          - "6379:6379"
        restart: always

    ysf_nginx:
        build: nginx
        ports:
          - "88:80"
          - "8300:8000"
          - "8380:8080"
        depends_on:
            - ysf_php_fpm
            - ysf_php_fpm_latest  
        links:
            - ysf_php_fpm
            - ysf_php_fpm_latest
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        restart: always

    ysf_php_fpm:
        build: php-fpm
        ports:
            - "9101:9000"
            - "3101:3001"
            - "3100:3000"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        depends_on:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
        restart: always
    
    ysf_php_fpm_latest:
        build: php-fpm-latest
        ports:
            - "9105:9000"
            - "3104:3001"
            - "3103:3000"
        volumes:
            - ./www:/var/www:cached
            - ./logs/nginx:/var/www/var/logs:cached
        depends_on:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
        links:
            - ysf_postgres
            - ysf_mysql
            - ysf_redis
        restart: always

    ysf_adminer:
        image: adminer
        ports:
            - 8071:8080
        depends_on:
            - ysf_postgres
            - ysf_mysql
        links:
            - ysf_postgres
            - ysf_mysql
        restart: always

    keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: ysf_postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        KEYCLOAK_USER: postgres
        KEYCLOAK_PASSWORD: postgres
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8689:8080
      depends_on:
        - ysf_adminer
        - ysf_postgres
      links:
        - ysf_adminer
        - ysf_postgres
      restart: always
